### ISSUE TITLE
Allowing `freq_tables` to create a table without `subtotals` or `totals`

### ISSUE THREAD

**Issue by edwardhuh** [thepolicylab/ZenTables#6]
Currently, `subtotals` and `totals` are required when generating `freq_tables`.
Specifically, this [warning](https://github.com/thepolicylab/ZenTables/blob/d9ab66d8345399ce8b11f7561e834157499204a6/src/zentables/zentables.py#L502) in `_internal_freq_table` function fundamentally restricts any flexibility for the user.

Therefore, I would appreciate the development of:
- [ ] Allowing users to produce frequency tables without `props`
- [ ] without `subtotals` but just `totals`
- [ ] without `subtotals` and `totals`
- [ ] providing additional `ValueErrors` for `props` to ensure that the user can get greater understanding of how to use the command, rather than simply "overriding" the settings.

**Comment by digicosmos86** [comment]
Very fair. Working on it
