### ISSUE TITLE
I got this Error !

### ISSUE THREAD

**Issue by tfr2003** [thepolicylab/ZenTables#8]
ImportError: cannot import name 'FilePathOrBuffer' from 'pandas.io.formats.style' (/opt/anaconda3/lib/python3.9/site-packages/pandas/io/formats/style.py)

**Comment by jhconning** [comment]
Same here, but the underlying issue, I think, is that it doesn't properly pip install in many environments because this is requiring older versions of several dependencies:

```
> pip install zentables

Collecting zentables
  Downloading ZenTables-0.2.3-py3-none-any.whl (15 kB)
Requirement already satisfied: pandas<2.0.0,>=1.3.0 in c:\users\jconn\anaconda3\lib\site-packages (from zentables) (1.4.2)
Collecting Jinja2<4.0.0,>=3.0.1
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
sphinx-book-theme 0.1.6 requires docutils<0.17,>=0.15, but you have docutils 0.17.1 which is incompatible.
pydata-sphinx-theme 0.6.3 requires docutils<0.17, but you have docutils 0.17.1 which is incompatible.
jupyter-book 0.12.0 requires jsonschema<4, but you have jsonschema 4.4.0 which is incompatible.
jupyter-book 0.12.0 requires jupytext<1.12,>=1.11.2, but you have jupytext 1.13.7 which is incompatible.
Successfully installed Jinja2-3.1.2 zentables-0.2.3
```

**Comment by digicosmos86** [comment]
Thank you all! This package uses some of the classes from Pandas 1.3.0. If there is no reason for you to use a lower version than 1.3.0, upgrading pandas would solve the issue.

**Comment by pmedvedev** [comment]
Was there a solution to this issue? using pandas 1.4.3 and getting the same error.

**Comment by digicosmos86** [comment]
It seems the new version of pandas has changed some of its internal API which this package depends on. A temporary solution is to downgrade your pandas to 1.3.x. I will work on a more permanent solution to add support to newer pandas versions soon.

**Comment by pmedvedev** [comment]
that's great. seems to have done the temp fix. really neat library. appreciate all of the work.

**Comment by digicosmos86** [comment]
Thanks! Please stay tuned for the update
